// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package database

import (
	"context"
	"database/sql"
)

const addEndToAttendaceByID = `-- name: AddEndToAttendaceByID :one
update attendance set end = ?,hours =?-start where id = ?
RETURNING start,end,hours
`

type AddEndToAttendaceByIDParams struct {
	End   sql.NullInt64
	Start int64
	ID    int64
}

type AddEndToAttendaceByIDRow struct {
	Start int64
	End   sql.NullInt64
	Hours sql.NullInt64
}

func (q *Queries) AddEndToAttendaceByID(ctx context.Context, arg AddEndToAttendaceByIDParams) (AddEndToAttendaceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, addEndToAttendaceByID, arg.End, arg.Start, arg.ID)
	var i AddEndToAttendaceByIDRow
	err := row.Scan(&i.Start, &i.End, &i.Hours)
	return i, err
}

const createAttendanceStart = `-- name: CreateAttendanceStart :one
insert into attendance (start,emp_id)
values (?,?)
RETURNING id,start
`

type CreateAttendanceStartParams struct {
	Start int64
	EmpID int64
}

type CreateAttendanceStartRow struct {
	ID    int64
	Start int64
}

func (q *Queries) CreateAttendanceStart(ctx context.Context, arg CreateAttendanceStartParams) (CreateAttendanceStartRow, error) {
	row := q.db.QueryRowContext(ctx, createAttendanceStart, arg.Start, arg.EmpID)
	var i CreateAttendanceStartRow
	err := row.Scan(&i.ID, &i.Start)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
delete from attendance where id =?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const getActiveSessionByEmpID = `-- name: GetActiveSessionByEmpID :one
select id from attendance where emp_id = ? and end is null order by start desc limit 1
`

func (q *Queries) GetActiveSessionByEmpID(ctx context.Context, empID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByEmpID, empID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAttendanceByID = `-- name: GetAttendanceByID :one
select id, start, "end", hours, emp_id from attendance where id=?
`

func (q *Queries) GetAttendanceByID(ctx context.Context, id int64) (Attendance, error) {
	row := q.db.QueryRowContext(ctx, getAttendanceByID, id)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.Start,
		&i.End,
		&i.Hours,
		&i.EmpID,
	)
	return i, err
}

const getAttendanceByMonth = `-- name: GetAttendanceByMonth :many
select id, start, "end", hours, emp_id from attendance where start > ? and start < ? and emp_id =?
`

type GetAttendanceByMonthParams struct {
	Start   int64
	Start_2 int64
	EmpID   int64
}

func (q *Queries) GetAttendanceByMonth(ctx context.Context, arg GetAttendanceByMonthParams) ([]Attendance, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceByMonth, arg.Start, arg.Start_2, arg.EmpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Start,
			&i.End,
			&i.Hours,
			&i.EmpID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendaceByID = `-- name: UpdateAttendaceByID :exec
update attendance set start = ?, end =?, hours=?,emp_id=? where id=?
`

type UpdateAttendaceByIDParams struct {
	Start int64
	End   sql.NullInt64
	Hours sql.NullInt64
	EmpID int64
	ID    int64
}

func (q *Queries) UpdateAttendaceByID(ctx context.Context, arg UpdateAttendaceByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAttendaceByID,
		arg.Start,
		arg.End,
		arg.Hours,
		arg.EmpID,
		arg.ID,
	)
	return err
}
