// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package database

import (
	"context"
)

const createEmployee = `-- name: CreateEmployee :one
insert into employees (name)
values (?)
RETURNING id
`

func (q *Queries) CreateEmployee(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEmployee, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
delete from employees where id =?
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmployee, id)
	return err
}

const getEmployees = `-- name: GetEmployees :many
select id, name from employees
`

func (q *Queries) GetEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, getEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
