// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Attendance struct {
	ID    int64
	Start int64
	End   sql.NullInt64
	Hours sql.NullInt64
	EmpID int64
}

type Employee struct {
	ID   int64
	Name string
}

type Setting struct {
	Key   string
	Value string
}
