// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package database

import (
	"context"
)

const addSet = `-- name: AddSet :exec
insert into settings(key,value)
values (?,?)
`

type AddSetParams struct {
	Key   string
	Value string
}

func (q *Queries) AddSet(ctx context.Context, arg AddSetParams) error {
	_, err := q.db.ExecContext(ctx, addSet, arg.Key, arg.Value)
	return err
}

const getSettings = `-- name: GetSettings :many
select "key", value from settings
`

func (q *Queries) GetSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, getSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSet = `-- name: UpdateSet :exec
update settings set value = ? where key = ?
`

type UpdateSetParams struct {
	Value string
	Key   string
}

func (q *Queries) UpdateSet(ctx context.Context, arg UpdateSetParams) error {
	_, err := q.db.ExecContext(ctx, updateSet, arg.Value, arg.Key)
	return err
}
